name: Encoder & Decoder Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cd ${{github.workspace}}/build && make -j4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./tests
